export interface Kotoba {
  id: number;
  kanji: string;
  hiragana?: string;
  romaji: string;
  indonesian: string;
  english: string;
  category?: string;
  iconName?: string;
}

export const KOTOBA_LIST: Kotoba[] = [
  { id: 1, kanji: "自動車", hiragana: "じどうしゃ", romaji: "Jidousha", indonesian: "Mobil / Kendaraan roda empat", english: "Car / Automobile", category: "Umum", iconName: "Car" },
  { id: 2, kanji: "整備", hiragana: "せいび", romaji: "Seibi", indonesian: "Perawatan / Pemeliharaan", english: "Maintenance", category: "Umum", iconName: "Wrench" },
  { id: 3, kanji: "エンジン", hiragana: "エンジン", romaji: "Enjin", indonesian: "Mesin", english: "Engine", category: "Suku Cadang", iconName: "Cpu" },
  { id: 4, kanji: "タイヤ", hiragana: "タイヤ", romaji: "Taiya", indonesian: "Ban", english: "Tire", category: "Suku Cadang", iconName: "CircleDot" },
  { id: 5, kanji: "ブレーキ", hiragana: "ブレーキ", romaji: "Bureeki", indonesian: "Rem", english: "Brake", category: "Suku Cadang", iconName: "Octagon" },
  { id: 6, kanji: "点検", hiragana: "てんけん", romaji: "Tenken", indonesian: "Pemeriksaan / Inspeksi", english: "Inspection / Check", category: "Tindakan", iconName: "Search" },
  { id: 7, kanji: "交換", hiragana: "こうかん", romaji: "Koukan", indonesian: "Penggantian", english: "Replacement / Exchange", category: "Tindakan", iconName: "RefreshCw" },
  { id: 8, kanji: "修理", hiragana: "しゅうり", romaji: "Shuuri", indonesian: "Perbaikan", english: "Repair", category: "Tindakan", iconName: "PenTool" },
  { id: 9, kanji: "安全", hiragana: "あんぜん", romaji: "Anzen", indonesian: "Keamanan / Keselamatan", english: "Safety", category: "Umum", iconName: "ShieldCheck" },
  { id: 10, kanji: "確認", hiragana: "かくにん", romaji: "Kakunin", indonesian: "Konfirmasi / Pengecekan", english: "Confirmation / Check", category: "Tindakan", iconName: "CheckSquare" },
  { id: 11, kanji: "工具", hiragana: "こうぐ", romaji: "Kougu", indonesian: "Peralatan (Tools)", english: "Tools", category: "Alat", iconName: "Hammer" },
  { id: 12, kanji: "レンチ", hiragana: "レンチ", romaji: "Renchi", indonesian: "Kunci pas / Wrench", english: "Wrench", category: "Alat", iconName: "Wrench" },
  { id: 13, kanji: "ドライバー", hiragana: "ドライバー", romaji: "Doraibaa", indonesian: "Obeng / Screwdriver", english: "Screwdriver", category: "Alat", iconName: "PenTool" },
  { id: 14, kanji: "オイル", hiragana: "オイル", romaji: "Oiru", indonesian: "Oli / Minyak pelumas", english: "Oil / Lubricant", category: "Cairan", iconName: "Droplet" },
  { id: 15, kanji: "燃料", hiragana: "ねんりょう", romaji: "Nenryou", indonesian: "Bahan Bakar", english: "Fuel", category: "Cairan", iconName: "Flame" },
  { id: 16, kanji: "ガソリン", hiragana: "ガソリン", romaji: "Gasorin", indonesian: "Bensin", english: "Gasoline", category: "Cairan", iconName: "Fuel" },
  { id: 17, kanji: "軽油", hiragana: "けいゆ", romaji: "Keiyu", indonesian: "Solar (Diesel)", english: "Diesel Fuel", category: "Cairan", iconName: "Fuel" },
  { id: 18, kanji: "冷却水", hiragana: "れいきゃくすい", romaji: "Reikyakusui", indonesian: "Air pendingin (Coolant)", english: "Coolant / Cooling Water", category: "Cairan", iconName: "Thermometer" },
  { id: 19, kanji: "異常", hiragana: "いじょう", romaji: "Ijou", indonesian: "Abnormal / Tidak normal", english: "Abnormal / Anomaly", category: "Kondisi", iconName: "AlertTriangle" },
  { id: 20, kanji: "正常", hiragana: "せいじょう", romaji: "Seijou", indonesian: "Normal", english: "Normal", category: "Kondisi", iconName: "CheckCircle2" },
  { id: 21, kanji: "摩耗", hiragana: "まもう", romaji: "Mamou", indonesian: "Aus / Keausan", english: "Wear / Abrasion", category: "Kondisi", iconName: "Activity" },
  { id: 22, kanji: "漏れ", hiragana: "もれ", romaji: "More", indonesian: "Bocor / Kebocoran", english: "Leak / Leakage", category: "Kondisi", iconName: "Droplets" },
  { id: 23, kanji: "測定", hiragana: "そくてい", romaji: "Sokutei", indonesian: "Pengukuran", english: "Measurement", category: "Tindakan", iconName: "Ruler" },
  { id: 24, kanji: "規定", hiragana: "きてい", romaji: "Kitei", indonesian: "Standar / Regulasi", english: "Standard / Regulation", category: "Umum", iconName: "FileText" },
  { id: 25, kanji: "部品", hiragana: "ぶひん", romaji: "Buhin", indonesian: "Suku Cadang / Part", english: "Parts / Components", category: "Suku Cadang", iconName: "Hexagon" },
  { id: 26, kanji: "緩み", hiragana: "ゆるみ", romaji: "Yurumi", indonesian: "Kendor / Kelonggaran", english: "Looseness", category: "Kondisi", iconName: "Unlock" },
  { id: 27, kanji: "締付け", hiragana: "しめつけ", romaji: "Shimetsuke", indonesian: "Pengencangan", english: "Tightening", category: "Tindakan", iconName: "Lock" },
  { id: 28, kanji: "清掃", hiragana: "せいそう", romaji: "Seisou", indonesian: "Pembersihan", english: "Cleaning", category: "Tindakan", iconName: "Sparkles" },
  { id: 29, kanji: "調整", hiragana: "ちょうせい", romaji: "Chousei", indonesian: "Penyetelan / Adjusting", english: "Adjustment", category: "Tindakan", iconName: "Sliders" },
  { id: 30, kanji: "作業", hiragana: "さぎょう", romaji: "Sagyou", indonesian: "Pekerjaan", english: "Work / Operation", category: "Umum", iconName: "Briefcase" },
  { id: 31, kanji: "排気ガス", hiragana: "はいきガス", romaji: "Haikigasu", indonesian: "Gas buang / Knalpot", english: "Exhaust Gas", category: "Umum", iconName: "CloudFog" },
  { id: 32, kanji: "バッテリー", hiragana: "バッテリー", romaji: "Batterii", indonesian: "Aki / Baterai", english: "Battery", category: "Suku Cadang", iconName: "Battery" },
  { id: 33, kanji: "ボルト", hiragana: "ボルト", romaji: "Boruto", indonesian: "Baut", english: "Bolt", category: "Suku Cadang", iconName: "NutOff" },
  { id: 34, kanji: "ナット", hiragana: "ナット", romaji: "Natto", indonesian: "Mur", english: "Nut", category: "Suku Cadang", iconName: "Hexagon" },
  { id: 35, kanji: "ジャッキ", hiragana: "ジャッキ", romaji: "Jakki", indonesian: "Dongkrak", english: "Jack", category: "Alat", iconName: "ArrowUpFromLine" },
  { id: 36, kanji: "リフト", hiragana: "リフト", romaji: "Rifuto", indonesian: "Lift hidrolik", english: "Lift (Hydraulic)", category: "Alat", iconName: "ArrowUpCircle" },
  { id: 37, kanji: "グリース", hiragana: "グリース", romaji: "Guriisu", indonesian: "Gemuk / Grease", english: "Grease", category: "Cairan", iconName: "Droplet" },
  { id: 38, kanji: "空気圧", hiragana: "くうきあつ", romaji: "Kuukiatsu", indonesian: "Tekanan udara", english: "Air Pressure", category: "Kondisi", iconName: "Gauge" },
  { id: 39, kanji: "亀裂", hiragana: "きれつ", romaji: "Kiretsu", indonesian: "Retak", english: "Crack", category: "Kondisi", iconName: "Zap" },
  { id: 40, kanji: "損傷", hiragana: "そんしょう", romaji: "Sonshou", indonesian: "Kerusakan", english: "Damage", category: "Kondisi", iconName: "HeartCrack" },
  { id: 41, kanji: "火災", hiragana: "かさい", romaji: "Kasai", indonesian: "Kebakaran", english: "Fire", category: "Kondisi", iconName: "Flame" },
  { id: 42, kanji: "保護具", hiragana: "ほごぐ", romaji: "Hogogu", indonesian: "Alat pelindung diri", english: "Protective Equipment", category: "Alat", iconName: "HardHat" },
  { id: 43, kanji: "手袋", hiragana: "てぶくろ", romaji: "Tebukuro", indonesian: "Sarung tangan", english: "Gloves", category: "Alat", iconName: "Hand" },
  { id: 44, kanji: "メガネ", hiragana: "メガネ", romaji: "Megane", indonesian: "Kacamata (pelindung)", english: "Safety Glasses", category: "Alat", iconName: "Glasses" },
  { id: 45, kanji: "トルクレンチ", hiragana: "トルクレンチ", romaji: "Torukurenchi", indonesian: "Kunci momen / Torque wrench", english: "Torque Wrench", category: "Alat", iconName: "Wrench" },
  { id: 46, kanji: "ダイヤルゲージ", hiragana: "ダイヤルゲージ", romaji: "Daiyarugeeji", indonesian: "Dial gauge", english: "Dial Gauge", category: "Alat", iconName: "Gauge" },
  { id: 47, kanji: "マイクロメーター", hiragana: "マイクロメーター", romaji: "Maikuromeetaa", indonesian: "Micrometer", english: "Micrometer", category: "Alat", iconName: "Ruler" },
  { id: 48, kanji: "ノギス", hiragana: "ノギス", romaji: "Nogisu", indonesian: "Jangka sorong / Vernier caliper", english: "Vernier Caliper", category: "Alat", iconName: "Ruler" },
  { id: 49, kanji: "すき間", hiragana: "すきま", romaji: "Sukima", indonesian: "Celah / Clearance", english: "Clearance / Gap", category: "Kondisi", iconName: "SplitSquareHorizontal" },
  { id: 50, kanji: "ラジエーター", hiragana: "ラジエーター", romaji: "Rajieetaa", indonesian: "Radiator", english: "Radiator", category: "Suku Cadang", iconName: "ThermometerSnowflake" },
  { id: 51, kanji: "プライヤー", hiragana: "プライヤー", romaji: "Puraiyaa", indonesian: "Tang / Pliers", english: "Pliers", category: "Alat", iconName: "Scissors" },
  { id: 52, kanji: "ハンマー", hiragana: "ハンマー", romaji: "Hanmaa", indonesian: "Palu / Hammer", english: "Hammer", category: "Alat", iconName: "Hammer" },
  { id: 53, kanji: "スパナ", hiragana: "スパナ", romaji: "Supana", indonesian: "Kunci pas (Spanner)", english: "Spanner", category: "Alat", iconName: "Wrench" },
  { id: 54, kanji: "リジッドラック", hiragana: "リジッドラック", romaji: "Rijiddorakku", indonesian: "Jack stand", english: "Rigid Rack / Jack Stand", category: "Alat", iconName: "Triangle" },
  { id: 55, kanji: "シックネスゲージ", hiragana: "シックネスゲージ", romaji: "Shikkunesugeeji", indonesian: "Thickness gauge / Feeler gauge", english: "Thickness Gauge", category: "Alat", iconName: "Menu" },
  { id: 56, kanji: "サーキットテスター", hiragana: "サーキットテスター", romaji: "Saakittotesutaa", indonesian: "Multitester (Sirkuit tester)", english: "Circuit Tester / Multimeter", category: "Alat", iconName: "Activity" },
  { id: 57, kanji: "サスペンション", hiragana: "サスペンション", romaji: "Sasupenshon", indonesian: "Suspensi", english: "Suspension", category: "Suku Cadang", iconName: "Spring" },
  { id: 58, kanji: "ショックアブソーバー", hiragana: "ショックアブソーバー", romaji: "Shokkuabusoubaa", indonesian: "Peredam kejut", english: "Shock Absorber", category: "Suku Cadang", iconName: "ArrowDownToLine" },
  { id: 59, kanji: "クラッチ", hiragana: "クラッチ", romaji: "Kuracchi", indonesian: "Kopling", english: "Clutch", category: "Suku Cadang", iconName: "Disc" },
  { id: 60, kanji: "トランスミッション", hiragana: "トランスミッション", romaji: "Toransumisshon", indonesian: "Transmisi", english: "Transmission", category: "Suku Cadang", iconName: "Settings" },
  { id: 61, kanji: "プロペラシャフト", hiragana: "プロペラシャフト", romaji: "Puroperashafuto", indonesian: "Poros propeler / Gardan", english: "Propeller Shaft", category: "Suku Cadang", iconName: "GitMerge" },
  { id: 62, kanji: "マフラー", hiragana: "マフラー", romaji: "Mafuraa", indonesian: "Knalpot / Muffler", english: "Muffler / Silencer", category: "Suku Cadang", iconName: "Wind" },
  { id: 63, kanji: "フィルター", hiragana: "フィルター", romaji: "Firutaa", indonesian: "Saringan / Filter", english: "Filter", category: "Suku Cadang", iconName: "Filter" },
  { id: 64, kanji: "外す", hiragana: "はずす", romaji: "Hazusu", indonesian: "Melepas / Mencopot", english: "To remove", category: "Kata Kerja", iconName: "MinusCircle" },
  { id: 65, kanji: "取り付ける", hiragana: "とりつける", romaji: "Toritsukeru", indonesian: "Memasang", english: "To install / attach", category: "Kata Kerja", iconName: "PlusCircle" },
  { id: 66, kanji: "回す", hiragana: "まわす", romaji: "Mawasu", indonesian: "Memutar", english: "To turn / rotate", category: "Kata Kerja", iconName: "RotateCw" },
  { id: 67, kanji: "踏む", hiragana: "ふむ", romaji: "Fumu", indonesian: "Menginjak", english: "To step on", category: "Kata Kerja", iconName: "ArrowDownCircle" },
  { id: 68, kanji: "引く", hiragana: "ひく", romaji: "Hiku", indonesian: "Menarik", english: "To pull", category: "Kata Kerja", iconName: "ArrowLeftCircle" },
  { id: 69, kanji: "押し込む", hiragana: "おしこむ", romaji: "Oshikomu", indonesian: "Mendorong masuk", english: "To push in", category: "Kata Kerja", iconName: "ArrowRightCircle" },
  { id: 70, kanji: "緩める", hiragana: "ゆるめる", romaji: "Yurumeru", indonesian: "Mengendurkan", english: "To loosen", category: "Kata Kerja", iconName: "Unlock" },
  { id: 71, kanji: "締める", hiragana: "しめる", romaji: "Shimeru", indonesian: "Mengencangkan", english: "To tighten", category: "Kata Kerja", iconName: "Lock" },
  { id: 72, kanji: "まっすぐ", hiragana: "まっすぐ", romaji: "Massugu", indonesian: "Lurus / Langsung", english: "Straight", category: "Kata Keterangan", iconName: "MoveUp" },
  { id: 73, kanji: "強く", hiragana: "つよく", romaji: "Tsuyoku", indonesian: "Dengan kuat", english: "Strongly", category: "Kata Keterangan", iconName: "Zap" },
  { id: 74, kanji: "軽く", hiragana: "かるく", romaji: "Karuku", indonesian: "Dengan ringan / Pelan", english: "Lightly", category: "Kata Keterangan", iconName: "Feather" },
  { id: 75, kanji: "定期的に", hiragana: "ていきてきに", romaji: "Teikiteki ni", indonesian: "Secara berkala / Rutin", english: "Periodically / Regularly", category: "Kata Keterangan", iconName: "Clock" },
  { id: 76, kanji: "直ちに", hiragana: "ただちに", romaji: "Tadachini", indonesian: "Segera / Langsung", english: "Immediately", category: "Kata Keterangan", iconName: "FastForward" },
  { id: 77, kanji: "十分", hiragana: "じゅうぶん", romaji: "Juubun", indonesian: "Cukup / Memadai", english: "Enough / Sufficient", category: "Kata Keterangan", iconName: "CheckCircle2" },
  { id: 78, kanji: "必ず", hiragana: "かならず", romaji: "Kanarazu", indonesian: "Pasti / Harus", english: "Always / Without fail", category: "Kata Keterangan", iconName: "AlertCircle" }
];
