export interface Kotoba {
  id: number;
  kanji: string;
  romaji: string;
  indonesian: string;
  english: string;
  category?: string;
}

export const KOTOBA_LIST: Kotoba[] = [
  { id: 1, kanji: "自動車", romaji: "Jidousha", indonesian: "Mobil / Kendaraan roda empat", english: "Car / Automobile", category: "Umum" },
  { id: 2, kanji: "整備", romaji: "Seibi", indonesian: "Perawatan / Pemeliharaan", english: "Maintenance", category: "Umum" },
  { id: 3, kanji: "エンジン", romaji: "Enjin", indonesian: "Mesin", english: "Engine", category: "Suku Cadang" },
  { id: 4, kanji: "タイヤ", romaji: "Taiya", indonesian: "Ban", english: "Tire", category: "Suku Cadang" },
  { id: 5, kanji: "ブレーキ", romaji: "Bureeki", indonesian: "Rem", english: "Brake", category: "Suku Cadang" },
  { id: 6, kanji: "点検", romaji: "Tenken", indonesian: "Pemeriksaan / Inspeksi", english: "Inspection / Check", category: "Tindakan" },
  { id: 7, kanji: "交換", romaji: "Koukan", indonesian: "Penggantian", english: "Replacement / Exchange", category: "Tindakan" },
  { id: 8, kanji: "修理", romaji: "Shuuri", indonesian: "Perbaikan", english: "Repair", category: "Tindakan" },
  { id: 9, kanji: "安全", romaji: "Anzen", indonesian: "Keamanan / Keselamatan", english: "Safety", category: "Umum" },
  { id: 10, kanji: "確認", romaji: "Kakunin", indonesian: "Konfirmasi / Pengecekan", english: "Confirmation / Check", category: "Tindakan" },
  { id: 11, kanji: "工具", romaji: "Kougu", indonesian: "Peralatan (Tools)", english: "Tools", category: "Alat" },
  { id: 12, kanji: "レンチ", romaji: "Renchi", indonesian: "Kunci pas / Wrench", english: "Wrench", category: "Alat" },
  { id: 13, kanji: "ドライバー", romaji: "Doraibaa", indonesian: "Obeng / Screwdriver", english: "Screwdriver", category: "Alat" },
  { id: 14, kanji: "オイル", romaji: "Oiru", indonesian: "Oli / Minyak pelumas", english: "Oil / Lubricant", category: "Cairan" },
  { id: 15, kanji: "燃料", romaji: "Nenryou", indonesian: "Bahan Bakar", english: "Fuel", category: "Cairan" },
  { id: 16, kanji: "ガソリン", romaji: "Gasorin", indonesian: "Bensin", english: "Gasoline", category: "Cairan" },
  { id: 17, kanji: "軽油", romaji: "Keiyu", indonesian: "Solar (Diesel)", english: "Diesel Fuel", category: "Cairan" },
  { id: 18, kanji: "冷却水", romaji: "Reikyakusui", indonesian: "Air pendingin (Coolant)", english: "Coolant / Cooling Water", category: "Cairan" },
  { id: 19, kanji: "異常", romaji: "Ijou", indonesian: "Abnormal / Tidak normal", english: "Abnormal / Anomaly", category: "Kondisi" },
  { id: 20, kanji: "正常", romaji: "Seijou", indonesian: "Normal", english: "Normal", category: "Kondisi" },
  { id: 21, kanji: "摩耗", romaji: "Mamou", indonesian: "Aus / Keausan", english: "Wear / Abrasion", category: "Kondisi" },
  { id: 22, kanji: "漏れ", romaji: "More", indonesian: "Bocor / Kebocoran", english: "Leak / Leakage", category: "Kondisi" },
  { id: 23, kanji: "測定", romaji: "Sokutei", indonesian: "Pengukuran", english: "Measurement", category: "Tindakan" },
  { id: 24, kanji: "規定", romaji: "Kitei", indonesian: "Standar / Regulasi", english: "Standard / Regulation", category: "Umum" },
  { id: 25, kanji: "部品", romaji: "Buhin", indonesian: "Suku Cadang / Part", english: "Parts / Components", category: "Suku Cadang" },
  { id: 26, kanji: "緩み", romaji: "Yurumi", indonesian: "Kendor / Kelonggaran", english: "Looseness", category: "Kondisi" },
  { id: 27, kanji: "締付け", romaji: "Shimetsuke", indonesian: "Pengencangan", english: "Tightening", category: "Tindakan" },
  { id: 28, kanji: "清掃", romaji: "Seisou", indonesian: "Pembersihan", english: "Cleaning", category: "Tindakan" },
  { id: 29, kanji: "調整", romaji: "Chousei", indonesian: "Penyetelan / Adjusting", english: "Adjustment", category: "Tindakan" },
  { id: 30, kanji: "作業", romaji: "Sagyou", indonesian: "Pekerjaan", english: "Work / Operation", category: "Umum" },
  { id: 31, kanji: "排気ガス", romaji: "Haikigasu", indonesian: "Gas buang / Knalpot", english: "Exhaust Gas", category: "Umum" },
  { id: 32, kanji: "バッテリー", romaji: "Batterii", indonesian: "Aki / Baterai", english: "Battery", category: "Suku Cadang" },
  { id: 33, kanji: "ボルト", romaji: "Boruto", indonesian: "Baut", english: "Bolt", category: "Suku Cadang" },
  { id: 34, kanji: "ナット", romaji: "Natto", indonesian: "Mur", english: "Nut", category: "Suku Cadang" },
  { id: 35, kanji: "ジャッキ", romaji: "Jakki", indonesian: "Dongkrak", english: "Jack", category: "Alat" },
  { id: 36, kanji: "リフト", romaji: "Rifuto", indonesian: "Lift hidrolik", english: "Lift (Hydraulic)", category: "Alat" },
  { id: 37, kanji: "グリース", romaji: "Guriisu", indonesian: "Gemuk / Grease", english: "Grease", category: "Cairan" },
  { id: 38, kanji: "空気圧", romaji: "Kuukiatsu", indonesian: "Tekanan udara", english: "Air Pressure", category: "Kondisi" },
  { id: 39, kanji: "亀裂", romaji: "Kiretsu", indonesian: "Retak", english: "Crack", category: "Kondisi" },
  { id: 40, kanji: "損傷", romaji: "Sonshou", indonesian: "Kerusakan", english: "Damage", category: "Kondisi" },
  { id: 41, kanji: "火災", romaji: "Kasai", indonesian: "Kebakaran", english: "Fire", category: "Kondisi" },
  { id: 42, kanji: "保護具", romaji: "Hogogu", indonesian: "Alat pelindung diri", english: "Protective Equipment", category: "Alat" },
  { id: 43, kanji: "手袋", romaji: "Tebukuro", indonesian: "Sarung tangan", english: "Gloves", category: "Alat" },
  { id: 44, kanji: "メガネ", romaji: "Megane", indonesian: "Kacamata (pelindung)", english: "Safety Glasses", category: "Alat" },
  { id: 45, kanji: "トルクレンチ", romaji: "Torukurenchi", indonesian: "Kunci momen / Torque wrench", english: "Torque Wrench", category: "Alat" },
  { id: 46, kanji: "ダイヤルゲージ", romaji: "Daiyarugeeji", indonesian: "Dial gauge", english: "Dial Gauge", category: "Alat" },
  { id: 47, kanji: "マイクロメーター", romaji: "Maikuromeetaa", indonesian: "Micrometer", english: "Micrometer", category: "Alat" },
  { id: 48, kanji: "ノギス", romaji: "Nogisu", indonesian: "Jangka sorong / Vernier caliper", english: "Vernier Caliper", category: "Alat" },
  { id: 49, kanji: "すき間", romaji: "Sukima", indonesian: "Celah / Clearance", english: "Clearance / Gap", category: "Kondisi" },
  { id: 50, kanji: "ラジエーター", romaji: "Rajieetaa", indonesian: "Radiator", english: "Radiator", category: "Suku Cadang" },
  { id: 51, kanji: "プライヤー", romaji: "Puraiyaa", indonesian: "Tang / Pliers", english: "Pliers", category: "Alat" },
  { id: 52, kanji: "ハンマー", romaji: "Hanmaa", indonesian: "Palu / Hammer", english: "Hammer", category: "Alat" },
  { id: 53, kanji: "スパナ", romaji: "Supana", indonesian: "Kunci pas (Spanner)", english: "Spanner", category: "Alat" },
  { id: 54, kanji: "リジッドラック", romaji: "Rijiddorakku", indonesian: "Jack stand", english: "Rigid Rack / Jack Stand", category: "Alat" },
  { id: 55, kanji: "シックネスゲージ", romaji: "Shikkunesugeeji", indonesian: "Thickness gauge / Feeler gauge", english: "Thickness Gauge", category: "Alat" },
  { id: 56, kanji: "サーキットテスター", romaji: "Saakittotesutaa", indonesian: "Multitester (Sirkuit tester)", english: "Circuit Tester / Multimeter", category: "Alat" },
  { id: 57, kanji: "サスペンション", romaji: "Sasupenshon", indonesian: "Suspensi", english: "Suspension", category: "Suku Cadang" },
  { id: 58, kanji: "ショックアブソーバー", romaji: "Shokkuabusoubaa", indonesian: "Peredam kejut", english: "Shock Absorber", category: "Suku Cadang" },
  { id: 59, kanji: "クラッチ", romaji: "Kuracchi", indonesian: "Kopling", english: "Clutch", category: "Suku Cadang" },
  { id: 60, kanji: "トランスミッション", romaji: "Toransumisshon", indonesian: "Transmisi", english: "Transmission", category: "Suku Cadang" },
  { id: 61, kanji: "プロペラシャフト", romaji: "Puroperashafuto", indonesian: "Poros propeler / Gardan", english: "Propeller Shaft", category: "Suku Cadang" },
  { id: 62, kanji: "マフラー", romaji: "Mafuraa", indonesian: "Knalpot / Muffler", english: "Muffler / Silencer", category: "Suku Cadang" },
  { id: 63, kanji: "フィルター", romaji: "Firutaa", indonesian: "Saringan / Filter", english: "Filter", category: "Suku Cadang" },
  { id: 64, kanji: "外す", romaji: "Hazusu", indonesian: "Melepas / Mencopot", english: "To remove", category: "Kata Kerja" },
  { id: 65, kanji: "取り付ける", romaji: "Toritsukeru", indonesian: "Memasang", english: "To install / attach", category: "Kata Kerja" },
  { id: 66, kanji: "回す", romaji: "Mawasu", indonesian: "Memutar", english: "To turn / rotate", category: "Kata Kerja" },
  { id: 67, kanji: "踏む", romaji: "Fumu", indonesian: "Menginjak", english: "To step on", category: "Kata Kerja" },
  { id: 68, kanji: "引く", romaji: "Hiku", indonesian: "Menarik", english: "To pull", category: "Kata Kerja" },
  { id: 69, kanji: "押し込む", romaji: "Oshikomu", indonesian: "Mendorong masuk", english: "To push in", category: "Kata Kerja" },
  { id: 70, kanji: "緩める", romaji: "Yurumeru", indonesian: "Mengendurkan", english: "To loosen", category: "Kata Kerja" },
  { id: 71, kanji: "締める", romaji: "Shimeru", indonesian: "Mengencangkan", english: "To tighten", category: "Kata Kerja" },
  { id: 72, kanji: "まっすぐ", romaji: "Massugu", indonesian: "Lurus / Langsung", english: "Straight", category: "Kata Keterangan" },
  { id: 73, kanji: "強く", romaji: "Tsuyoku", indonesian: "Dengan kuat", english: "Strongly", category: "Kata Keterangan" },
  { id: 74, kanji: "軽く", romaji: "Karuku", indonesian: "Dengan ringan / Pelan", english: "Lightly", category: "Kata Keterangan" },
  { id: 75, kanji: "定期的に", romaji: "Teikiteki ni", indonesian: "Secara berkala / Rutin", english: "Periodically / Regularly", category: "Kata Keterangan" },
  { id: 76, kanji: "直ちに", romaji: "Tadachini", indonesian: "Segera / Langsung", english: "Immediately", category: "Kata Keterangan" },
  { id: 77, kanji: "十分", romaji: "Juubun", indonesian: "Cukup / Memadai", english: "Enough / Sufficient", category: "Kata Keterangan" },
  { id: 78, kanji: "必ず", romaji: "Kanarazu", indonesian: "Pasti / Harus", english: "Always / Without fail", category: "Kata Keterangan" }
];
