-- SSW Jidousha Seibi Database Schema Setup with Translation Support

-- 1. PROFILES TABLE
CREATE TABLE IF NOT EXISTS public.profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    password TEXT DEFAULT 'seibi123' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow public write access to profiles" ON public.profiles FOR ALL USING (true);

-- Seed profiles
INSERT INTO public.profiles (name)
VALUES 
    ('Angga'),
    ('Dean'),
    ('Rian'),
    ('Agus'),
    ('Sandriya')
ON CONFLICT (name) DO NOTHING;


-- 2. QUESTIONS TABLE
-- Support for multilingual testing (Japanese JP, Indonesian ID, English EN)
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_jp TEXT NOT NULL,
    question_id TEXT NOT NULL,
    question_en TEXT NOT NULL,
    options_jp JSONB NOT NULL, -- e.g., ["O", "X"]
    options_id JSONB NOT NULL, -- e.g., ["Benar", "Salah"]
    options_en JSONB NOT NULL, -- e.g., ["True", "False"]
    correct_index INTEGER NOT NULL,
    explanation_jp TEXT,
    explanation_id TEXT,
    explanation_en TEXT,
    image_url TEXT, -- Path to extracted image in /images
    category TEXT DEFAULT 'Umum' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to questions" ON public.questions FOR SELECT USING (true);
CREATE POLICY "Allow public write access to questions" ON public.questions FOR ALL USING (true);

-- Seed Multilingual Questions using the extracted image assets
INSERT INTO public.questions (
    question_jp, question_id, question_en, 
    options_jp, options_id, options_en, 
    correct_index, 
    explanation_jp, explanation_id, explanation_en, 
    image_url, category
)
VALUES 
    (
        'ガソリンエンジンの ねんりょう は、けいゆです。',
        'Bahan bakar untuk mesin bensin adalah solar (minyak ringan).',
        'The fuel for a gasoline engine is diesel oil (light oil).',
        '["O", "X"]', '["Benar", "Salah"]', '["True", "False"]',
        1,
        'けいゆはディーゼルエンジンの燃料です。ガソリンはガソリンエンジンの燃料です。',
        'Solar (light oil) adalah bahan bakar untuk mesin diesel. Bensin (gasoline) adalah bahan bakar untuk mesin bensin.',
        'Diesel oil (light oil) is the fuel for diesel engines. Gasoline is the fuel for gasoline engines.',
        NULL, 'Mesin'
    ),
    (
        'これは ダイヤルゲージです。',
        'Alat pada gambar ini adalah dial gauge.',
        'The tool in this image is a dial gauge.',
        '["O", "X"]', '["Benar", "Salah"]', '["True", "False"]',
        0,
        '画像の測定器はダイヤルゲージで、微小な寸法の変位を測定するために使用されます。',
        'Alat ukur pada gambar adalah dial gauge (pengukur celah/kelonggaran), yang digunakan untuk mengukur penyimpangan dimensi yang sangat kecil.',
        'The measuring instrument in the image is a dial gauge, which is used to measure small displacements in dimensions.',
        '/images/page_4_img_1.jpg', 'Sasis'
    ),
    (
        'ブレーキライニングは、こうかんぶひんです。',
        'Brake lining (kampas rem) adalah suku cadang pengganti (consumable part).',
        'Brake lining is a replacement part.',
        '["O", "X"]', '["Benar", "Salah"]', '["True", "False"]',
        0,
        'ブレーキライニングは摩擦によって摩耗するため、定期的な交換が必要な消耗部品です。',
        'Brake lining akan aus karena gesekan, sehingga merupakan suku cadang habis pakai yang memerlukan penggantian berkala.',
        'Brake lining wears down due to friction, making it a consumable part that requires periodic replacement.',
        NULL, 'Sasis'
    ),
    (
        'れいきゃく そうち の らじえーた は、ふぁん で あたためます。',
        'Radiator pada sistem pendingin dipanaskan oleh kipas.',
        'The radiator of the cooling system is heated by the fan.',
        '["O", "X"]', '["Benar", "Salah"]', '["True", "False"]',
        1,
        'ラジエーターはファンによって冷やされます（温めるのではありません）。',
        'Radiator didinginkan oleh aliran udara dari kipas (bukan dipanaskan).',
        'The radiator is cooled by the air flow from the fan (not heated).',
        NULL, 'Mesin'
    ),
    (
        'デプス・ゲージはタイヤの溝の深さを測定する工具です。',
        'Depth gauge adalah alat yang digunakan untuk mengukur kedalaman alur ban.',
        'A depth gauge is a tool used to measure the depth of tire treads.',
        '["O", "X"]', '["Benar", "Salah"]', '["True", "False"]',
        0,
        'デプスゲージ（depth gauge）は、タイヤの摩耗状態を確認するために溝の深さを測定します。',
        'Depth gauge (alat pengukur kedalaman) digunakan untuk mengukur kedalaman alur ban guna memeriksa tingkat keausan ban.',
        'A depth gauge is used to measure the depth of tire grooves to check the wear condition of the tire.',
        '/images/page_20_img_1.jpg', 'Sasis'
    );


-- 3. PRACTICE HISTORY TABLE
CREATE TABLE IF NOT EXISTS public.practice_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    score INTEGER NOT NULL,
    total_questions INTEGER NOT NULL,
    answered_correctly INTEGER NOT NULL,
    answers_json JSONB, -- Format: [{"question_id": 1, "selected": 0, "correct": true}]
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.practice_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to practice_history" ON public.practice_history FOR SELECT USING (true);
CREATE POLICY "Allow public write access to practice_history" ON public.practice_history FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public all access to practice_history" ON public.practice_history FOR ALL USING (true);
